In [1]:
import numpy as np

a = np.arange(10)
b = np.asarray([a])
c = b.T
print(a.shape)
print(b.shape)
print(c.shape)


(10,)
(1, 10)
(10, 1)


In [2]:
for i in [10, 20, 30, 40, 50, 60, 70]:
    a = np.array([2**i, 1])
    print(a)
    print(type(a))
    print(a.dtype)


[1024    1]
<class 'numpy.ndarray'>
int64
[1048576       1]
<class 'numpy.ndarray'>
int64
[1073741824          1]
<class 'numpy.ndarray'>
int64
[1099511627776             1]
<class 'numpy.ndarray'>
int64
[1125899906842624                1]
<class 'numpy.ndarray'>
int64
[1152921504606846976                   1]
<class 'numpy.ndarray'>
int64
[1180591620717411303424 1]
<class 'numpy.ndarray'>
object


In [3]:
# list to array --> new id
l = [1, 2, 3, 4]
a = np.array(l)
s = a[:2]
ss = a[:2].copy()
l[0] = 99
print("l", l, id(l))
print("a", a, id(a))
print("s", s, id(s))
print("ss", ss, id(ss))


l [99, 2, 3, 4] 140642396302784
a [1 2 3 4] 140642396316528
s [1 2] 140642396314704
ss [1 2] 140642396316816


In [4]:
# array to array --> refenenced
l = [1, 2, 3, 4]
a = np.array(l)
s = a[:2]
ss = a[:2].copy()
s[0] = 99
print("l", l, id(l))
print("a", a, id(a))
print("s", s, id(s))
print("ss", ss, id(ss))


l [1, 2, 3, 4] 140642396303168
a [99  2  3  4] 140642396317296
s [99  2] 140642396317200
ss [1 2] 140642396316528


In [5]:
# a: base, b: reshaped (referneced)
a = np.arange(16)
b = a.reshape(4, 4)

print(a)
print(b)

a[0] = 99
print(a)
print(b)

b[1, 1] = 88
print(a)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[99  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[99  1  2  3  4 88  6  7  8  9 10 11 12 13 14 15]
[[99  1  2  3]
 [ 4 88  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
# change shape variable --> shape is changed
a = np.arange(16)
b = a.reshape(2, -1)
print(b)
b.shape = 4, -1
print(b)
b.shape = -1, 2
print(b)


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


# Practice


## 계산기1

Numpy ndarray 2개를 입력으로 받아 연산결과를 출력하는 계산기를 클래스로 만든다.

- add, sub, mul, div의 네 가지 함수를 구현할 것
- (3, 3) matrix 와 (3, 3) matrix에 대해 결과를 확인할 것 (mul)
- (3, 3) matrix와 (3,) vector에 대해 결과를 확인할 것 (add)
- (3, 3) matrix와 (3,1) vector에 대해 결과를 확인할 것 (sub)
- (3, 3) matrix와 scalar에 대해 결과를 확인할 것 (div)


## 계산기2

위 계산기에 ndarray 1개를 받는 연산을 추가한다.

- sin, cos, log 초월함수를 계산한다.
- 평균과 분산을 계산한다. 이 때, 계산할 axis를 받는다.
- Square matrix에 대해 역행렬을 계산한다. (np.linalg 이용)
- 계산한 역행렬과 원래 행렬을 곱해 I가 나오는지 확인한다.


## 계산기3

ReLU(Rectified Linear Unit)는 머신 러닝 모델에서 활성 함수(activation function)로 자주 사용된다.
ReLU는 input의 각 element가 0보다 작으면 0을 내보내고, 양수이면 그대로 통과시킨다.
y = x (if x> 0), 0 (else)

한편, Leaky ReLU는 음수일 때 기울기가 존재한다.
y = x (if x>0), ax (else)

위 계산기에 ReLU, Leaky ReLU(a=0.02)를 추가하여라.
(np.maximum, np.where 이용)


In [7]:
import numpy as np


class Calculator:
    @staticmethod
    def add(x, y):
        return x + y

    @staticmethod
    def sub(x, y):
        return x - y

    @staticmethod
    def mul(x, y):
        return x * y

    @staticmethod
    def div(x, y):
        return x / y

    @staticmethod
    def sin(x):
        return np.sin(x)

    @staticmethod
    def cos(x):
        return np.cos(x)

    @staticmethod
    def log(x, base=np.e):
        if base == np.e:
            return np.log(x)
        return np.log(x) / np.log(base)

    @staticmethod
    def mean(x, axis=None):
        # return x.mean(axis=axis)
        return np.mean(x, axis=axis)

    # Variance
    @staticmethod
    def var(x, axis=None):
        return np.var(x, axis=axis)

    @staticmethod
    def inv(x):
        if (x.ndim != 2) or (x.shape[0] != x.shape[1]):
            print("Inverse should be computed in square matrix.")
            return None
        return np.linalg.inv(x)

    @staticmethod
    def relu(x):
        return np.maximum(x, 0)

    @staticmethod
    def leaky_relu(x, a=0.02):
        return np.where(x > 0, x, x * a)
        # np.where(cond, x, y) ->
        # if condition:
        #     x
        # else:
        #     y


In [8]:
calculator = Calculator()
calculator.relu(np.linspace(-10, 10, 100))


array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.1010101 ,  0.3030303 ,  0.50505051,  0.70707071,  0.90909091,
        1.11111111,  1.31313131,  1.51515152,  1.71717172,  1.91919192,
        2.12121212,  2.32323232,  2.52525253,  2.72727273,  2.92929293,
        3.13131313,  3.33333333,  3.53535354,  3.73737374,  3.93

## Pooling Layer

Average pooling은 (s, s) 타일마다 평균을 계산한다. (s=stride)
S=2인 경우, (100, 100) 크기의 2D ndarray를 넣으면 (50, 50) 크기의 결과값이 나와야 한다.

- np.random.uniform을 사용하여 (100, 100) 크기의Uniform ~ [0, 1] array를 만든다.
- S=2로 average_pooling을 구현하라.

(힌트: reshape를 이용해 차원을 높인 뒤 특정 axis에 대해 mean을 구하고 다시 원래 2D로 돌아온다)


In [10]:
import numpy as np

S = 4
L = 100

A = np.random.uniform(size=L**2).reshape(L, L)
print(A.shape)
reshaped_A = A.reshape(S**2, int(L / S), -1)
print(reshaped_A.shape)
pooled_A = np.mean(reshaped_A, axis=0)

print(pooled_A)
print(pooled_A.shape)


(100, 100)
(16, 25, 25)
[[0.45409608 0.5735206  0.57036062 0.58362722 0.42000592 0.50524907
  0.42049504 0.51578369 0.40431951 0.51639603 0.52713002 0.45933018
  0.47977487 0.42278218 0.46482022 0.47092995 0.55771019 0.59192147
  0.51793485 0.45928413 0.4946133  0.36195386 0.41796546 0.49555283
  0.58217983]
 [0.60403367 0.3958242  0.42582383 0.56300834 0.54586978 0.45615581
  0.54833724 0.57018976 0.61018678 0.52620228 0.48980639 0.52702448
  0.50182723 0.54462251 0.41906549 0.46522176 0.48775396 0.60449868
  0.43837951 0.44383806 0.47229019 0.63951261 0.53870652 0.38368377
  0.41510953]
 [0.59289603 0.54954527 0.52473889 0.51881103 0.44905529 0.5655316
  0.46807348 0.5098536  0.57988165 0.55256261 0.52969573 0.4658544
  0.47614452 0.49864904 0.47857144 0.42840103 0.45667409 0.63658496
  0.48696622 0.47763952 0.59204344 0.58929305 0.40535119 0.46375955
  0.54395486]
 [0.63352433 0.57928711 0.51198778 0.46507576 0.48437038 0.49098091
  0.52545036 0.49238619 0.45961343 0.5191286  0.4840